#!/bin/sh
grep -A4 -m1 NSTEP dihAngle-180_ene.out > allout.txt
grep -A4 -m1 NSTEP dihAngle-180_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle-179_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle-178_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle-177_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle-176_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle-175_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle-174_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle-173_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle-172_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle-171_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle-170_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle-169_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle-168_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle-167_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle-166_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle-165_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle-164_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle-163_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle-162_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle-161_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle-160_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle-159_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle-158_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle-157_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle-156_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle-155_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle-154_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle-153_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle-152_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle-151_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle-150_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle-149_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle-148_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle-147_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle-146_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle-145_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle-144_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle-143_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle-142_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle-141_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle-140_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle-139_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle-138_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle-137_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle-136_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle-135_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle-134_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle-133_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle-132_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle-131_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle-130_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle-129_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle-128_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle-127_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle-126_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle-125_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle-124_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle-123_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle-122_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle-121_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle-120_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle-119_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle-118_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle-117_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle-116_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle-115_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle-114_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle-113_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle-112_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle-111_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle-110_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle-109_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle-108_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle-107_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle-106_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle-105_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle-104_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle-103_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle-102_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle-101_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle-100_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle-99_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle-98_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle-97_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle-96_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle-95_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle-94_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle-93_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle-92_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle-91_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle-90_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle-89_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle-88_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle-87_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle-86_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle-85_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle-84_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle-83_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle-82_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle-81_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle-80_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle-79_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle-78_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle-77_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle-76_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle-75_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle-74_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle-73_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle-72_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle-71_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle-70_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle-69_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle-68_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle-67_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle-66_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle-65_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle-64_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle-63_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle-62_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle-61_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle-60_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle-59_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle-58_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle-57_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle-56_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle-55_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle-54_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle-53_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle-52_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle-51_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle-50_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle-49_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle-48_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle-47_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle-46_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle-45_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle-44_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle-43_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle-42_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle-41_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle-40_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle-39_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle-38_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle-37_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle-36_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle-35_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle-34_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle-33_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle-32_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle-31_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle-30_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle-29_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle-28_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle-27_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle-26_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle-25_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle-24_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle-23_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle-22_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle-21_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle-20_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle-19_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle-18_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle-17_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle-16_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle-15_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle-14_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle-13_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle-12_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle-11_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle-10_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle-9_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle-8_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle-7_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle-6_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle-5_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle-4_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle-3_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle-2_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle-1_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle0_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle1_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle2_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle3_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle4_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle5_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle6_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle7_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle8_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle9_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle10_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle11_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle12_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle13_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle14_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle15_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle16_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle17_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle18_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle19_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle20_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle21_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle22_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle23_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle24_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle25_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle26_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle27_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle28_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle29_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle30_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle31_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle32_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle33_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle34_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle35_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle36_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle37_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle38_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle39_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle40_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle41_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle42_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle43_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle44_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle45_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle46_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle47_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle48_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle49_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle50_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle51_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle52_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle53_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle54_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle55_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle56_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle57_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle58_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle59_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle60_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle61_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle62_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle63_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle64_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle65_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle66_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle67_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle68_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle69_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle70_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle71_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle72_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle73_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle74_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle75_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle76_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle77_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle78_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle79_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle80_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle81_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle82_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle83_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle84_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle85_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle86_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle87_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle88_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle89_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle90_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle91_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle92_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle93_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle94_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle95_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle96_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle97_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle98_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle99_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle100_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle101_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle102_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle103_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle104_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle105_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle106_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle107_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle108_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle109_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle110_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle111_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle112_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle113_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle114_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle115_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle116_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle117_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle118_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle119_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle120_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle121_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle122_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle123_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle124_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle125_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle126_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle127_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle128_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle129_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle130_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle131_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle132_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle133_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle134_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle135_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle136_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle137_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle138_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle139_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle140_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle141_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle142_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle143_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle144_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle145_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle146_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle147_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle148_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle149_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle150_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle151_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle152_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle153_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle154_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle155_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle156_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle157_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle158_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle159_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle160_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle161_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle162_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle163_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle164_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle165_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle166_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle167_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle168_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle169_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle170_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle171_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle172_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle173_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle174_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle175_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle176_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle177_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle178_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle179_ene.out >> allout.txt
grep -A4 -m1 NSTEP dihAngle180_ene.out >> allout.txt
